// Code generated by entc, DO NOT EDIT.

package permission

const (
	// Label holds the string label denoting the permission type in the database.
	Label = "permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldContentTypeID holds the string denoting the content_type_id field in the database.
	FieldContentTypeID = "content_type_id"
	// FieldModelCode holds the string denoting the model_code field in the database.
	FieldModelCode = "model_code"
	// Table holds the table name of the permission in the database.
	Table = "permissions"
)

// Columns holds all SQL columns for permission fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldContentTypeID,
	FieldModelCode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ModelCodeValidator is a validator for the "model_code" field. It is called by the builders before save.
	ModelCodeValidator func(string) error
)
