// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgbbiao/xadminent/ent/predicate"
	"github.com/wgbbiao/xadminent/ent/xadminpermission"
	"github.com/wgbbiao/xadminent/ent/xadminrole"
	"github.com/wgbbiao/xadminent/ent/xadminuser"
)

// XadminUserQuery is the builder for querying XadminUser entities.
type XadminUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.XadminUser
	// eager-loading edges.
	withRoles       *XadminRoleQuery
	withPermissions *XadminPermissionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the XadminUserQuery builder.
func (xuq *XadminUserQuery) Where(ps ...predicate.XadminUser) *XadminUserQuery {
	xuq.predicates = append(xuq.predicates, ps...)
	return xuq
}

// Limit adds a limit step to the query.
func (xuq *XadminUserQuery) Limit(limit int) *XadminUserQuery {
	xuq.limit = &limit
	return xuq
}

// Offset adds an offset step to the query.
func (xuq *XadminUserQuery) Offset(offset int) *XadminUserQuery {
	xuq.offset = &offset
	return xuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (xuq *XadminUserQuery) Unique(unique bool) *XadminUserQuery {
	xuq.unique = &unique
	return xuq
}

// Order adds an order step to the query.
func (xuq *XadminUserQuery) Order(o ...OrderFunc) *XadminUserQuery {
	xuq.order = append(xuq.order, o...)
	return xuq
}

// QueryRoles chains the current query on the "roles" edge.
func (xuq *XadminUserQuery) QueryRoles() *XadminRoleQuery {
	query := &XadminRoleQuery{config: xuq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := xuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := xuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(xadminuser.Table, xadminuser.FieldID, selector),
			sqlgraph.To(xadminrole.Table, xadminrole.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, xadminuser.RolesTable, xadminuser.RolesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(xuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPermissions chains the current query on the "permissions" edge.
func (xuq *XadminUserQuery) QueryPermissions() *XadminPermissionQuery {
	query := &XadminPermissionQuery{config: xuq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := xuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := xuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(xadminuser.Table, xadminuser.FieldID, selector),
			sqlgraph.To(xadminpermission.Table, xadminpermission.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, xadminuser.PermissionsTable, xadminuser.PermissionsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(xuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first XadminUser entity from the query.
// Returns a *NotFoundError when no XadminUser was found.
func (xuq *XadminUserQuery) First(ctx context.Context) (*XadminUser, error) {
	nodes, err := xuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{xadminuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (xuq *XadminUserQuery) FirstX(ctx context.Context) *XadminUser {
	node, err := xuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first XadminUser ID from the query.
// Returns a *NotFoundError when no XadminUser ID was found.
func (xuq *XadminUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = xuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{xadminuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (xuq *XadminUserQuery) FirstIDX(ctx context.Context) int {
	id, err := xuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single XadminUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one XadminUser entity is found.
// Returns a *NotFoundError when no XadminUser entities are found.
func (xuq *XadminUserQuery) Only(ctx context.Context) (*XadminUser, error) {
	nodes, err := xuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{xadminuser.Label}
	default:
		return nil, &NotSingularError{xadminuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (xuq *XadminUserQuery) OnlyX(ctx context.Context) *XadminUser {
	node, err := xuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only XadminUser ID in the query.
// Returns a *NotSingularError when more than one XadminUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (xuq *XadminUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = xuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = &NotSingularError{xadminuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (xuq *XadminUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := xuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of XadminUsers.
func (xuq *XadminUserQuery) All(ctx context.Context) ([]*XadminUser, error) {
	if err := xuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return xuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (xuq *XadminUserQuery) AllX(ctx context.Context) []*XadminUser {
	nodes, err := xuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of XadminUser IDs.
func (xuq *XadminUserQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := xuq.Select(xadminuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (xuq *XadminUserQuery) IDsX(ctx context.Context) []int {
	ids, err := xuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (xuq *XadminUserQuery) Count(ctx context.Context) (int, error) {
	if err := xuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return xuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (xuq *XadminUserQuery) CountX(ctx context.Context) int {
	count, err := xuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (xuq *XadminUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := xuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return xuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (xuq *XadminUserQuery) ExistX(ctx context.Context) bool {
	exist, err := xuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the XadminUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (xuq *XadminUserQuery) Clone() *XadminUserQuery {
	if xuq == nil {
		return nil
	}
	return &XadminUserQuery{
		config:          xuq.config,
		limit:           xuq.limit,
		offset:          xuq.offset,
		order:           append([]OrderFunc{}, xuq.order...),
		predicates:      append([]predicate.XadminUser{}, xuq.predicates...),
		withRoles:       xuq.withRoles.Clone(),
		withPermissions: xuq.withPermissions.Clone(),
		// clone intermediate query.
		sql:    xuq.sql.Clone(),
		path:   xuq.path,
		unique: xuq.unique,
	}
}

// WithRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (xuq *XadminUserQuery) WithRoles(opts ...func(*XadminRoleQuery)) *XadminUserQuery {
	query := &XadminRoleQuery{config: xuq.config}
	for _, opt := range opts {
		opt(query)
	}
	xuq.withRoles = query
	return xuq
}

// WithPermissions tells the query-builder to eager-load the nodes that are connected to
// the "permissions" edge. The optional arguments are used to configure the query builder of the edge.
func (xuq *XadminUserQuery) WithPermissions(opts ...func(*XadminPermissionQuery)) *XadminUserQuery {
	query := &XadminPermissionQuery{config: xuq.config}
	for _, opt := range opts {
		opt(query)
	}
	xuq.withPermissions = query
	return xuq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.XadminUser.Query().
//		GroupBy(xadminuser.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (xuq *XadminUserQuery) GroupBy(field string, fields ...string) *XadminUserGroupBy {
	group := &XadminUserGroupBy{config: xuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := xuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return xuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.XadminUser.Query().
//		Select(xadminuser.FieldUsername).
//		Scan(ctx, &v)
//
func (xuq *XadminUserQuery) Select(fields ...string) *XadminUserSelect {
	xuq.fields = append(xuq.fields, fields...)
	return &XadminUserSelect{XadminUserQuery: xuq}
}

func (xuq *XadminUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range xuq.fields {
		if !xadminuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if xuq.path != nil {
		prev, err := xuq.path(ctx)
		if err != nil {
			return err
		}
		xuq.sql = prev
	}
	return nil
}

func (xuq *XadminUserQuery) sqlAll(ctx context.Context) ([]*XadminUser, error) {
	var (
		nodes       = []*XadminUser{}
		_spec       = xuq.querySpec()
		loadedTypes = [2]bool{
			xuq.withRoles != nil,
			xuq.withPermissions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &XadminUser{config: xuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, xuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := xuq.withRoles; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*XadminUser, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Roles = []*XadminRole{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*XadminUser)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   xadminuser.RolesTable,
				Columns: xadminuser.RolesPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(xadminuser.RolesPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, xuq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "roles": %w`, err)
		}
		query.Where(xadminrole.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "roles" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Roles = append(nodes[i].Edges.Roles, n)
			}
		}
	}

	if query := xuq.withPermissions; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*XadminUser, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Permissions = []*XadminPermission{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*XadminUser)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   xadminuser.PermissionsTable,
				Columns: xadminuser.PermissionsPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(xadminuser.PermissionsPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, xuq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "permissions": %w`, err)
		}
		query.Where(xadminpermission.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "permissions" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Permissions = append(nodes[i].Edges.Permissions, n)
			}
		}
	}

	return nodes, nil
}

func (xuq *XadminUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := xuq.querySpec()
	_spec.Node.Columns = xuq.fields
	if len(xuq.fields) > 0 {
		_spec.Unique = xuq.unique != nil && *xuq.unique
	}
	return sqlgraph.CountNodes(ctx, xuq.driver, _spec)
}

func (xuq *XadminUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := xuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (xuq *XadminUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   xadminuser.Table,
			Columns: xadminuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: xadminuser.FieldID,
			},
		},
		From:   xuq.sql,
		Unique: true,
	}
	if unique := xuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := xuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, xadminuser.FieldID)
		for i := range fields {
			if fields[i] != xadminuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := xuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := xuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := xuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := xuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (xuq *XadminUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(xuq.driver.Dialect())
	t1 := builder.Table(xadminuser.Table)
	columns := xuq.fields
	if len(columns) == 0 {
		columns = xadminuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if xuq.sql != nil {
		selector = xuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if xuq.unique != nil && *xuq.unique {
		selector.Distinct()
	}
	for _, p := range xuq.predicates {
		p(selector)
	}
	for _, p := range xuq.order {
		p(selector)
	}
	if offset := xuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := xuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// XadminUserGroupBy is the group-by builder for XadminUser entities.
type XadminUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (xugb *XadminUserGroupBy) Aggregate(fns ...AggregateFunc) *XadminUserGroupBy {
	xugb.fns = append(xugb.fns, fns...)
	return xugb
}

// Scan applies the group-by query and scans the result into the given value.
func (xugb *XadminUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := xugb.path(ctx)
	if err != nil {
		return err
	}
	xugb.sql = query
	return xugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (xugb *XadminUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := xugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (xugb *XadminUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(xugb.fields) > 1 {
		return nil, errors.New("ent: XadminUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := xugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (xugb *XadminUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := xugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (xugb *XadminUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = xugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = fmt.Errorf("ent: XadminUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (xugb *XadminUserGroupBy) StringX(ctx context.Context) string {
	v, err := xugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (xugb *XadminUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(xugb.fields) > 1 {
		return nil, errors.New("ent: XadminUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := xugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (xugb *XadminUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := xugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (xugb *XadminUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = xugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = fmt.Errorf("ent: XadminUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (xugb *XadminUserGroupBy) IntX(ctx context.Context) int {
	v, err := xugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (xugb *XadminUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(xugb.fields) > 1 {
		return nil, errors.New("ent: XadminUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := xugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (xugb *XadminUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := xugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (xugb *XadminUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = xugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = fmt.Errorf("ent: XadminUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (xugb *XadminUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := xugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (xugb *XadminUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(xugb.fields) > 1 {
		return nil, errors.New("ent: XadminUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := xugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (xugb *XadminUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := xugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (xugb *XadminUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = xugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = fmt.Errorf("ent: XadminUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (xugb *XadminUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := xugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (xugb *XadminUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range xugb.fields {
		if !xadminuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := xugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := xugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (xugb *XadminUserGroupBy) sqlQuery() *sql.Selector {
	selector := xugb.sql.Select()
	aggregation := make([]string, 0, len(xugb.fns))
	for _, fn := range xugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(xugb.fields)+len(xugb.fns))
		for _, f := range xugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(xugb.fields...)...)
}

// XadminUserSelect is the builder for selecting fields of XadminUser entities.
type XadminUserSelect struct {
	*XadminUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (xus *XadminUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := xus.prepareQuery(ctx); err != nil {
		return err
	}
	xus.sql = xus.XadminUserQuery.sqlQuery(ctx)
	return xus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (xus *XadminUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := xus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (xus *XadminUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(xus.fields) > 1 {
		return nil, errors.New("ent: XadminUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := xus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (xus *XadminUserSelect) StringsX(ctx context.Context) []string {
	v, err := xus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (xus *XadminUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = xus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = fmt.Errorf("ent: XadminUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (xus *XadminUserSelect) StringX(ctx context.Context) string {
	v, err := xus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (xus *XadminUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(xus.fields) > 1 {
		return nil, errors.New("ent: XadminUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := xus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (xus *XadminUserSelect) IntsX(ctx context.Context) []int {
	v, err := xus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (xus *XadminUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = xus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = fmt.Errorf("ent: XadminUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (xus *XadminUserSelect) IntX(ctx context.Context) int {
	v, err := xus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (xus *XadminUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(xus.fields) > 1 {
		return nil, errors.New("ent: XadminUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := xus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (xus *XadminUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := xus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (xus *XadminUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = xus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = fmt.Errorf("ent: XadminUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (xus *XadminUserSelect) Float64X(ctx context.Context) float64 {
	v, err := xus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (xus *XadminUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(xus.fields) > 1 {
		return nil, errors.New("ent: XadminUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := xus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (xus *XadminUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := xus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (xus *XadminUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = xus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{xadminuser.Label}
	default:
		err = fmt.Errorf("ent: XadminUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (xus *XadminUserSelect) BoolX(ctx context.Context) bool {
	v, err := xus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (xus *XadminUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := xus.sql.Query()
	if err := xus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
