// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgbbiao/xadminent/ent/predicate"
	"github.com/wgbbiao/xadminent/ent/xadmincontenttype"
)

// XadminContenttypeDelete is the builder for deleting a XadminContenttype entity.
type XadminContenttypeDelete struct {
	config
	hooks    []Hook
	mutation *XadminContenttypeMutation
}

// Where appends a list predicates to the XadminContenttypeDelete builder.
func (xcd *XadminContenttypeDelete) Where(ps ...predicate.XadminContenttype) *XadminContenttypeDelete {
	xcd.mutation.Where(ps...)
	return xcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (xcd *XadminContenttypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(xcd.hooks) == 0 {
		affected, err = xcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*XadminContenttypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			xcd.mutation = mutation
			affected, err = xcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(xcd.hooks) - 1; i >= 0; i-- {
			if xcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = xcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, xcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (xcd *XadminContenttypeDelete) ExecX(ctx context.Context) int {
	n, err := xcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (xcd *XadminContenttypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: xadmincontenttype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: xadmincontenttype.FieldID,
			},
		},
	}
	if ps := xcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, xcd.driver, _spec)
}

// XadminContenttypeDeleteOne is the builder for deleting a single XadminContenttype entity.
type XadminContenttypeDeleteOne struct {
	xcd *XadminContenttypeDelete
}

// Exec executes the deletion query.
func (xcdo *XadminContenttypeDeleteOne) Exec(ctx context.Context) error {
	n, err := xcdo.xcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{xadmincontenttype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (xcdo *XadminContenttypeDeleteOne) ExecX(ctx context.Context) {
	xcdo.xcd.ExecX(ctx)
}
