// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgbbiao/xadminent/ent/xadmincontenttype"
)

// XadminContenttypeCreate is the builder for creating a XadminContenttype entity.
type XadminContenttypeCreate struct {
	config
	mutation *XadminContenttypeMutation
	hooks    []Hook
}

// SetAppLabel sets the "app_label" field.
func (xcc *XadminContenttypeCreate) SetAppLabel(s string) *XadminContenttypeCreate {
	xcc.mutation.SetAppLabel(s)
	return xcc
}

// SetModel sets the "model" field.
func (xcc *XadminContenttypeCreate) SetModel(s string) *XadminContenttypeCreate {
	xcc.mutation.SetModel(s)
	return xcc
}

// SetCreatedAt sets the "created_at" field.
func (xcc *XadminContenttypeCreate) SetCreatedAt(t time.Time) *XadminContenttypeCreate {
	xcc.mutation.SetCreatedAt(t)
	return xcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (xcc *XadminContenttypeCreate) SetNillableCreatedAt(t *time.Time) *XadminContenttypeCreate {
	if t != nil {
		xcc.SetCreatedAt(*t)
	}
	return xcc
}

// SetUpdatedAt sets the "updated_at" field.
func (xcc *XadminContenttypeCreate) SetUpdatedAt(t time.Time) *XadminContenttypeCreate {
	xcc.mutation.SetUpdatedAt(t)
	return xcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (xcc *XadminContenttypeCreate) SetNillableUpdatedAt(t *time.Time) *XadminContenttypeCreate {
	if t != nil {
		xcc.SetUpdatedAt(*t)
	}
	return xcc
}

// Mutation returns the XadminContenttypeMutation object of the builder.
func (xcc *XadminContenttypeCreate) Mutation() *XadminContenttypeMutation {
	return xcc.mutation
}

// Save creates the XadminContenttype in the database.
func (xcc *XadminContenttypeCreate) Save(ctx context.Context) (*XadminContenttype, error) {
	var (
		err  error
		node *XadminContenttype
	)
	xcc.defaults()
	if len(xcc.hooks) == 0 {
		if err = xcc.check(); err != nil {
			return nil, err
		}
		node, err = xcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*XadminContenttypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = xcc.check(); err != nil {
				return nil, err
			}
			xcc.mutation = mutation
			if node, err = xcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(xcc.hooks) - 1; i >= 0; i-- {
			if xcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = xcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, xcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (xcc *XadminContenttypeCreate) SaveX(ctx context.Context) *XadminContenttype {
	v, err := xcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (xcc *XadminContenttypeCreate) Exec(ctx context.Context) error {
	_, err := xcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (xcc *XadminContenttypeCreate) ExecX(ctx context.Context) {
	if err := xcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (xcc *XadminContenttypeCreate) defaults() {
	if _, ok := xcc.mutation.CreatedAt(); !ok {
		v := xadmincontenttype.DefaultCreatedAt()
		xcc.mutation.SetCreatedAt(v)
	}
	if _, ok := xcc.mutation.UpdatedAt(); !ok {
		v := xadmincontenttype.DefaultUpdatedAt()
		xcc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (xcc *XadminContenttypeCreate) check() error {
	if _, ok := xcc.mutation.AppLabel(); !ok {
		return &ValidationError{Name: "app_label", err: errors.New(`ent: missing required field "XadminContenttype.app_label"`)}
	}
	if v, ok := xcc.mutation.AppLabel(); ok {
		if err := xadmincontenttype.AppLabelValidator(v); err != nil {
			return &ValidationError{Name: "app_label", err: fmt.Errorf(`ent: validator failed for field "XadminContenttype.app_label": %w`, err)}
		}
	}
	if _, ok := xcc.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "XadminContenttype.model"`)}
	}
	if v, ok := xcc.mutation.Model(); ok {
		if err := xadmincontenttype.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "XadminContenttype.model": %w`, err)}
		}
	}
	if _, ok := xcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "XadminContenttype.created_at"`)}
	}
	if _, ok := xcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "XadminContenttype.updated_at"`)}
	}
	return nil
}

func (xcc *XadminContenttypeCreate) sqlSave(ctx context.Context) (*XadminContenttype, error) {
	_node, _spec := xcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, xcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (xcc *XadminContenttypeCreate) createSpec() (*XadminContenttype, *sqlgraph.CreateSpec) {
	var (
		_node = &XadminContenttype{config: xcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: xadmincontenttype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: xadmincontenttype.FieldID,
			},
		}
	)
	if value, ok := xcc.mutation.AppLabel(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: xadmincontenttype.FieldAppLabel,
		})
		_node.AppLabel = value
	}
	if value, ok := xcc.mutation.Model(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: xadmincontenttype.FieldModel,
		})
		_node.Model = value
	}
	if value, ok := xcc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: xadmincontenttype.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := xcc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: xadmincontenttype.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// XadminContenttypeCreateBulk is the builder for creating many XadminContenttype entities in bulk.
type XadminContenttypeCreateBulk struct {
	config
	builders []*XadminContenttypeCreate
}

// Save creates the XadminContenttype entities in the database.
func (xccb *XadminContenttypeCreateBulk) Save(ctx context.Context) ([]*XadminContenttype, error) {
	specs := make([]*sqlgraph.CreateSpec, len(xccb.builders))
	nodes := make([]*XadminContenttype, len(xccb.builders))
	mutators := make([]Mutator, len(xccb.builders))
	for i := range xccb.builders {
		func(i int, root context.Context) {
			builder := xccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*XadminContenttypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, xccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, xccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, xccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (xccb *XadminContenttypeCreateBulk) SaveX(ctx context.Context) []*XadminContenttype {
	v, err := xccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (xccb *XadminContenttypeCreateBulk) Exec(ctx context.Context) error {
	_, err := xccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (xccb *XadminContenttypeCreateBulk) ExecX(ctx context.Context) {
	if err := xccb.Exec(ctx); err != nil {
		panic(err)
	}
}
