// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wgbbiao/xadminent/ent/predicate"
	"github.com/wgbbiao/xadminent/ent/xadminpermission"
)

// XadminPermissionDelete is the builder for deleting a XadminPermission entity.
type XadminPermissionDelete struct {
	config
	hooks    []Hook
	mutation *XadminPermissionMutation
}

// Where appends a list predicates to the XadminPermissionDelete builder.
func (xpd *XadminPermissionDelete) Where(ps ...predicate.XadminPermission) *XadminPermissionDelete {
	xpd.mutation.Where(ps...)
	return xpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (xpd *XadminPermissionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(xpd.hooks) == 0 {
		affected, err = xpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*XadminPermissionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			xpd.mutation = mutation
			affected, err = xpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(xpd.hooks) - 1; i >= 0; i-- {
			if xpd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = xpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, xpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (xpd *XadminPermissionDelete) ExecX(ctx context.Context) int {
	n, err := xpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (xpd *XadminPermissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: xadminpermission.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: xadminpermission.FieldID,
			},
		},
	}
	if ps := xpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, xpd.driver, _spec)
}

// XadminPermissionDeleteOne is the builder for deleting a single XadminPermission entity.
type XadminPermissionDeleteOne struct {
	xpd *XadminPermissionDelete
}

// Exec executes the deletion query.
func (xpdo *XadminPermissionDeleteOne) Exec(ctx context.Context) error {
	n, err := xpdo.xpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{xadminpermission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (xpdo *XadminPermissionDeleteOne) ExecX(ctx context.Context) {
	xpdo.xpd.ExecX(ctx)
}
